source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
  use_frameworks!

def shared_pods
    pod 'AlamofireObjectMapper', :git => 'https://github.com/tristanhimmelman/AlamofireObjectMapper.git'
    pod 'Alamofire', '~> 4.0'
    pod 'CRToast', '~> 0.0.7'
    pod 'R.swift'
end

target 'Cthullu' do
    shared_pods
end

target 'CthulluTests' do
  shared_pods
  inherit! :search_paths
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
